# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_distributor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_reply',
            name='subject',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nama_lengkap',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contact_reply',
            name='pesan',
            field=models.TextField(null=True),
        ),
    ]
