# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20171115_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_distributor',
            name='last_activity',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
