# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_session_distributor_last_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pembelian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField(null=True)),
                ('t_harga', models.IntegerField(null=True)),
                ('bahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Bahan')),
            ],
        ),
    ]
