# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_bahan_harga_satuan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=300, null=True)),
                ('email', models.CharField(max_length=300, null=True)),
                ('alamat', models.CharField(max_length=300, null=True)),
                ('telp', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pembelian',
            name='waktu_permintaan',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
