# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20171213_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembelian',
            name='status',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pembelian',
            name='suplier_id',
            field=models.IntegerField(null=True),
        ),
    ]
