# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20171214_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembelian',
            name='suplier_id',
        ),
        migrations.AddField(
            model_name='pembelian',
            name='sup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Suplier'),
        ),
    ]
